### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by AlexanderSiguenza** [ghostPlayerl5/Practico_3#1]
Buen trabajo te felicito, código ordenado y limpio, continua trabajando de esta manera , Pero te falto el documento pdf

Para continuar su formación por favor estudiar estos temas :
Patrones Diseño :  https://refactoring.guru/es/design-patterns/csharp
Código limpio : https://servocode.com/blog/clean-code-principles-in-c-aka-how-to-write-projects-that-dont-suck
Principios Solid : https://enmilocalfunciona.io/principios-solid/

**Comment by ghostPlayerl5** [comment]
Hola buenas tardes ingeniero, el documento pdf esta en una rama diferente.

**Comment by AlexanderSiguenza** [comment]
Gracias por la aclaración , nota actualizada
